/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This script generates reference ("exact") values for the logGamma function.
 * The generated values are stored sequentially in a binary file, as follows
 * x[0], f(x[0]), x[1], f(x[1]), ...
 * where f is the function being sampled.
 */
 
kill(all);

fpprec : 64;
f(x) := log(gamma(x));

sample(x, name) := block(
  y : [],
  for i : 1 while i <= length(x) do y : endcons(float(f(x[i])), y),
  xy : join(float(x), y),
  stream : openw_binary(name),
  write_binary_data(xy, stream),
  close(stream)
  );

x : append(makelist(bfloat(i / 1024), i, 1, 8192));
sample(x, "logGamma-01.dat");

x : makelist(bfloat(i / 8), i, 65, 8192);
sample(x, "logGamma-02.dat");

x : makelist(bfloat(i), i, 1025, 8192);
sample(x, "logGamma-03.dat");

x : makelist(bfloat(2**(i / 8)), i, 105, 8112);
sample(x, "logGamma-04.dat");
