/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.commons.math4.analysis.differentiation.finite;

import org.apache.commons.math4.fraction.BigFraction;
import org.apache.commons.math4.linear.FieldVector;
import org.junit.Assert;
import org.junit.Test;

/**
 * Tests for the coefficient generator.
 */
public class FiniteDifferenceCoefficientGeneratorTest {
    
    @Test
    public void testCentral() {	
	assertCoefficients(new FiniteDifference(FiniteDifferenceType.CENTRAL, 1, 2),
		new BigFraction(-1, 2), new BigFraction(0), new BigFraction(1, 2)); 
	
	assertCoefficients(new FiniteDifference(FiniteDifferenceType.CENTRAL, 1, 4),
		new BigFraction(1, 12), new BigFraction(-2, 3), new BigFraction(0), new BigFraction(2, 3), new BigFraction(-1, 12)); 

	assertCoefficients(new FiniteDifference(FiniteDifferenceType.CENTRAL, 2, 2),
		new BigFraction(1), new BigFraction(-2), new BigFraction(1)); 	
    }
        
    /**
     * Checks that the coefficients generated by the stencil are equal to the expected values. 
     * 
     * @param finiteDifference The stencil to check.
     * @param coefficients The expected coefficients.
     */
    private void assertCoefficients(final FiniteDifference finiteDifference, final BigFraction... coefficients) {
	FiniteDifferenceCoefficientGenerator generator = new FiniteDifferenceCoefficientGenerator(finiteDifference);
	FieldVector<BigFraction> generated = generator.getCoefficients();
	
	Assert.assertEquals(coefficients.length, generated.getDimension());
	
	for(int index = 0; index < coefficients.length; index++) {
	    Assert.assertEquals(coefficients[index], generated.getEntry(index));
	}
    }

}
